########## PRODUCTION environment ##########
spring:
  datasource:
    url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}