########## PRODUCTION environment ##########
spring:
  datasource:
    url: "jdbc:postgresql://db.avigyuspyyfdvvbppufi.supabase.co:5432/postgres?user=postgres&password=fGwqr1LjWJnVWtHL"
    username: "postgres"
    password: "fGwqr1LjWJnVWtHL"
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT}