spring:
  application:
    name: "Sayyara Backend"
  profiles:
    default: "dev"

server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: always
    include-message: always



springdoc:
  swagger-ui:
    url: /api/open-api.yaml
    path: /docs
