########## PRODUCTION environment ##########
spring:
  datasource:
    url: "jdbc:postgresql://containers-us-west-108.railway.app:6852/railway?user=postgres&password=Xioxdb5rkXhXsntt8J9k"
    username: "postgres"
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}