name: Deploy Backend to Railway

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Go to Backend
        run: cd backend

      - name: Deploy Backend
        run: railway up

# Modified from https://blog.railway.app/p/github-actions
